### ISSUE TITLE
Can't parse CAIDA warts file

### ISSUE THREAD

**Issue by eyalfoni** [alexmarder/MAP-IT#1]
I'm trying to run MAP-IT on CAIDA topology files. The software works perfectly on almost every file, but for a couple the following error arises.

Command: 
`python3 mapit.py -t trcrts/daily.l7.t3.c004006.20150604.sof-bg.warts.gz -b rtvws/routeviews-rv2-20170624-1200.pfx2as.gz -o as2org/20170401.as-org2info.txt.gz -w temp.csv`

Error: 
```
Traceback (most recent call last):
  File "mapit.py", line 201, in <module>
    main()
  File "mapit.py", line 126, in main
    adjacencies, addresses = create_adjacencies(args.traces, pool=args.pool)
  File "mapit.py", line 55, in create_adjacencies
    for new_adjacencies, new_addresses in pb.iterator(results):
  File "/Users/eyalfoni/Documents/Projects/CyberWrite/MAP-IT-master/progress.py", line 36, in iterator
    yield from iterable
  File "/Users/eyalfoni/Documents/Projects/CyberWrite/MAP-IT-master/trace.py", line 59, in process_trace_file
    for j in f:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 7931 (char 7930)
```

**Comment by alexmarder** [comment]
Sorry for taking so long to respond. Is your version of scamper is up to date? There are also occasional warts files that are corrupted, usually due to the memory card used on the Raspberry Pi getting corrupted.

**Comment by eyalfoni** [comment]
No worries - I don't remember exactly as this was awhile ago. 

Closing the issue b/c not relevant anymore. Thanks!
